# Nome do workflow
name: Deploy Frontend para Netlify

# Define que o pipeline será executado a cada push na branch 'main'
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Versão LTS estável para Angular

      - name: Cache de dependências
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Instalar dependências
        run: npm ci

      - name: Build da aplicação (Produção)
        # O comando ng build compila o Angular e otimiza para produção.
        run: npm run build -- --configuration production

      # Passo de Deploy para Netlify
      - name: Deploy para Netlify
        uses: netlify/actions/cli@master
        with:
          # O diretório que contém os arquivos estáticos após o build
          dir: 'dist/dinmonex-web/browser' 
          # O comando 'netlify deploy --prod' publica o site
          prod: true
        env:
          # Variáveis secretas que você deve configurar no GitHub Secrets
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
